apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: purchasesystem 
spec:
  type: ClusterIP
  replicas: 3
  template:
    metadata:
      labels:
        app: purchasesystem 
    spec:
      containers:
        - name: purchasesystem 
          image: admin9.azurecr.io/purchasesystem
          ports:
          - containerPort: 8080
