apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchasesystem
  labels:
    app: purchasesystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchasesystem
  template:
    metadata:
      labels:
        app: purchasesystem
    spec:
      containers:
        - name: purchasesystem
          image: username/purchasesystem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5